# Generated by Django 3.2.18 on 2023-12-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TotalStudents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('course_id', models.CharField(max_length=10)),
                ('total_students', models.IntegerField()),
            ],
        ),
    ]
