# Generated by Django 3.2.18 on 2023-12-13 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('total_students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='totalstudents',
            table='total_students',
        ),
    ]
