version: '3'

services:

### NGINX Server #########################################
    nginx:
      build:
        context: ./nginx


### Statistics API #######################################
    statistics_api:
      env_file: .env
      build:
        context: .
        dockerfile: ./Dockerfile
