version: '3'

networks:
#  backend_canvas-net:
#    external: true
  statistics_api-net:
    driver: bridge

services:

### NGINX ################################################
    nginx:
      env_file: .env
      build:
        context: ./nginx
        dockerfile: Dockerfile.dev
        args:
          - WEBSITES_PORT=${WEBSITES_PORT}
          - STATISTICS_API_HOST=statistics_api
      ports:
        - "${WEBSITES_PORT}:443"
      networks:
        - statistics_api-net
      depends_on:
        - statistics_api

### MariaDB-database #####################################
    api-database:
      env_file: .env
      image: mariadb:10.8
      command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      environment:
        - MARIADB_AUTO_UPGRADE=1
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - TZ=${WORKSPACE_TIMEZONE}
        - MYSQL_TCP_PORT=${DB_PORT}
        - MYSQL_UNIX_PORT=${DB_PORT}
      ports:
        - "${MYSQL_PORT}:3302"
      networks:
        statistics_api-net:
          aliases:
            - api-database


### Statistics API #######################################
    statistics_api:
      env_file: .env
      build:
        context: .
        dockerfile: Dockerfile.dev
      environment:
        - CA_FILE_NAME=${CA_FILE_NAME}
        - DB_HOST=api-database
        - DB_DATABASE=${MYSQL_DATABASE}
        - DB_USERNAME=${MYSQL_USER}
        - DB_PASSWORD=${MYSQL_PASSWORD}
        - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
        - DJANGO_DEBUG=True
        - DJANGO_ALLOWED_HOSTS=*
        - CANVAS_ACCOUNT_ID=${CANVAS_ACCOUNT_ID}
        - CANVAS_ACCESS_KEY=${CANVAS_ACCESS_KEY}
        - CANVAS_DOMAIN=${CANVAS_DOMAIN}
        - PULL_MEMBER_COUNTS_FROM_CANVAS_ON_STARTUP=${PULL_MEMBER_COUNTS_FROM_CANVAS_ON_STARTUP}
        - KPAS_DOMAIN=${KPAS_DOMAIN}
        - WEBSITES_PORT=${WEBSITES_PORT}
        - GUNICORN_TIMEOUT=${GUNICORN_TIMEOUT}
        - GUNICORN_LOG_LEVEL=${GUNICORN_LOG_LEVEL}
      networks:
#        - backend_canvas-net
        - statistics_api-net
      depends_on:
        - api-database
