version: '3'

networks:
  backend_canvas-net:
    external: true
  statistics_api-net:
    driver: bridge

services:


### NGINX ################################################
    nginx:
      build:
        context: ./nginx
      ports:
        - "8003:443"

### MySQL ################################################
    api-database:
      image: mysql:5.7.30
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - TZ=${WORKSPACE_TIMEZONE}
      ports:
        - "${MYSQL_PORT}:3306"
      networks:
        statistics_api-net:
          aliases:
            - api-database


### Statistics API #######################################
    statistics_api:
      env_file: .env
      build:
        context: .
        dockerfile: Dockerfile.dev
      environment:
        - CA_FILE_NAME=ca.crt
        - DB_HOST=api-database
        - DB_DATABASE=${MYSQL_DATABASE}
        - DB_USERNAME=${MYSQL_USER}
        - DB_PASSWORD=${MYSQL_PASSWORD}
        - DJANGO_SECRET_KEY="jasn9a32bu$$52xmncsvu@n(el4zczksb@hc=_ffm4o4ar1nah"
        - DJANGO_DEBUG=True
        - CANVAS_API_KEY="oRGcytCEFtGITFDrcfojCuUHwJCSjVvbcUSnHDUHM8oNv3SPz1LWNBboX06tkwt2"
      networks:
        - backend_canvas-net
        - statistics_api-net
      depends_on:
        - api-database
