FROM ubuntu:18.04
RUN groupadd -g 999 appuser && useradd -r -u 999 -g appuser appuser && apt update && apt install openssh-server python3 python3-pip python3-venv libmysqlclient-dev gdal-bin gosu -y && echo "root:Docker!" | chpasswd && /usr/bin/python3 -m venv /app/venv
RUN apt update && apt install iputils-ping net-tools dnsutils mysql-client vim -y
COPY requirements.txt /requirements.txt
RUN /app/venv/bin/python3 -m pip install -r /requirements.txt --default-timeout=100
COPY sshd_config sshd_setup.sh /etc/ssh/
COPY manage.py start_web_app.sh entrypoint.sh ca.crt wait-for-it.sh /app/
COPY statistics_api /app/statistics_api/
WORKDIR /app/
RUN chown appuser:appuser -R /app && chmod 700 /etc/ssh/sshd_setup.sh && /etc/ssh/sshd_setup.sh && find . -type d | grep -v "./venv" | xargs chmod 755 && find . -type f | grep -v "./venv" | xargs chmod 644 && chmod 700 entrypoint.sh start_web_app.sh wait-for-it.sh
ENV PYTHONPATH="/app"
CMD ["./wait-for-it.sh", "mysql:${MYSQL_PORT}", "-t", "3", "--", "/app/entrypoint.sh"]
