FROM ubuntu:18.04
COPY requirements.txt /requirements.txt
RUN groupadd -g 999 appuser && useradd -r -u 999 -g appuser appuser && apt update && apt install python3 python3-pip python3-venv libmysqlclient-dev -y && /usr/bin/python3 -m venv /app/venv
RUN apt update && apt install iputils-ping net-tools dnsutils mysql-client vim -y
RUN /app/venv/bin/python3 -m pip install -r /requirements.txt --default-timeout=100
COPY manage.py entrypoint.sh ca.crt wait-for-it.sh /app/
COPY statistics_api /app/statistics_api/
RUN chmod 700 /app/entrypoint.sh /app/wait-for-it.sh && chown appuser:appuser /app/entrypoint.sh /app/wait-for-it.sh
USER appuser
WORKDIR /app/
ENV PYTHONPATH="/app"
CMD ["./wait-for-it.sh", "mysql:${MYSQL_PORT}", "-t", "3", "--", "/app/entrypoint.sh"]
