# Generated by Django 3.0.7 on 2020-06-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseobservation',
            name='canvas_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='courseobservation',
            name='date_retrieved',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='canvas_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='groupcategory',
            name='canvas_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
