# Generated by Django 3.0.6 on 2020-05-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_api', '0002_auto_20200529_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupcategory',
            name='canvas_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
