# Generated by Django 3.0.7 on 2020-07-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_api', '0002_auto_20200629_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='organization_number',
            field=models.CharField(db_index=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='number_of_teachers',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='GroupToSchoolRelationship',
        ),
    ]
