# Generated by Django 3.0.7 on 2020-07-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_api', '0003_auto_20200706_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_id', models.IntegerField(unique=True)),
                ('number_of_teachers', models.IntegerField()),
                ('updated_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'county',
            },
        ),
    ]
