# Generated by Django 3.0.7 on 2020-06-23 09:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_api', '0003_auto_20200529_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseobservation',
            name='date_retrieved',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='courseobservation',
            table='course_observation',
        ),
    ]
