# Generated by Django 3.0.9 on 2020-09-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_api', '0004_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='year',
            field=models.IntegerField(default=2018),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='year',
            field=models.IntegerField(default=2019),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='county',
            name='county_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='school',
            name='organization_number',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterUniqueTogether(
            name='county',
            unique_together={('county_id', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='school',
            unique_together={('organization_number', 'year')},
        ),
    ]
