# Generated by Django 3.0.7 on 2020-06-24 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_api', '0005_school'),
    ]

    operations = [
        migrations.DeleteModel(
            name='School',
        ),
    ]
