# Generated by Django 3.2.13 on 2022-06-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_api', '0005_auto_20200901_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='aggregated',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
