# Generated by Django 3.2.13 on 2022-08-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_api', '0006_group_aggregated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='aggregated',
            field=models.BooleanField(default=False),
        ),
    ]
