# Generated by Django 4.2.10 on 2024-03-12 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_api', '0007_alter_group_aggregated'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='County',
                ),
                migrations.RemoveField(
                    model_name='group',
                    name='group_category',
                ),
                migrations.RemoveField(
                    model_name='groupcategory',
                    name='course',
                ),
                migrations.DeleteModel(
                    name='School',
                ),
                migrations.DeleteModel(
                    name='CourseObservation',
                ),
                migrations.DeleteModel(
                    name='Group',
                ),
                migrations.DeleteModel(
                    name='GroupCategory',
                ),
            ],
            database_operations=[],
        ),
    ]
