# Generated by Django 3.0.7 on 2020-06-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_api', '0007_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
