# Generated by Django 3.2.13 on 2022-09-01 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_api', '0007_alter_group_aggregated'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='group',
            table='canvas_group',
        ),
    ]
