# Generated by Django 3.0.7 on 2020-06-25 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_api', '0008_auto_20200624_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='updated_date',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='GroupToSchoolRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistics_api.Group')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistics_api.School')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
