# Generated by Django 3.0.7 on 2020-06-25 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_api', '0010_auto_20200625_0903'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grouptoschoolrelationship',
            unique_together={('group', 'school')},
        ),
        migrations.AlterModelTable(
            name='grouptoschoolrelationship',
            table='group_to_school_relationship',
        ),
    ]
