# Generated by Django 3.2.13 on 2022-07-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matomo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('label', models.CharField(max_length=255)),
                ('visits', models.IntegerField(blank=True, null=True)),
                ('sum_time_spent', models.IntegerField(blank=True, null=True)),
                ('average_time_spent', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('unique_visitors', models.IntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('bounce_rate', models.CharField(blank=True, max_length=10, null=True)),
                ('exit_rate', models.CharField(blank=True, max_length=10, null=True)),
                ('exit_visits', models.IntegerField(blank=True, null=True)),
                ('entry_visits', models.IntegerField(blank=True, null=True)),
                ('segment', models.CharField(max_length=255)),
            ],
        ),
    ]
