# Generated by Django 3.2.13 on 2022-07-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matomo', '0003_alter_pagestatistics_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagestatistics',
            name='segment',
            field=models.CharField(max_length=512),
        ),
    ]
