# Generated by Django 3.2.13 on 2022-07-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matomo', '0006_auto_20220722_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='visits',
            name='actions_new',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visits',
            name='actions_per_visit_new',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='visits',
            name='actions_per_visit_returning',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='visits',
            name='actions_returning',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visits',
            name='avg_time_on_site_new',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visits',
            name='avg_time_on_site_returning',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visits',
            name='bounce_count_new',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visits',
            name='bounce_count_returning',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visits',
            name='bounce_rate_new',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='visits',
            name='bounce_rate_returning',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='visits',
            name='max_actions_new',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visits',
            name='max_actions_returning',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visits',
            name='sum_visit_length_new',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visits',
            name='sum_visit_length_returning',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visits',
            name='unique_visitors_new',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visits',
            name='unique_visitors_returning',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visits',
            name='visits_new',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visits',
            name='visits_returning',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visits',
            name='unique_visitors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visits',
            name='visits',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
