# Generated by Django 3.2.13 on 2022-08-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matomo', '0007_auto_20220722_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagestatistics',
            name='segment',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
