# Generated by Django 3.2.18 on 2023-12-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matomo', '0008_alter_pagestatistics_segment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagestatistics',
            name='url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
