# Generated by Django 4.2.10 on 2024-03-12 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='CourseObservation',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('date_retrieved', models.DateTimeField(auto_now_add=True, db_index=True)),
                        ('canvas_id', models.IntegerField(db_index=True)),
                        ('name', models.CharField(max_length=255)),
                    ],
                    options={
                        'db_table': 'course_observation',
                    },
                ),
                migrations.CreateModel(
                    name='School',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('organization_number', models.CharField(max_length=9)),
                        ('number_of_teachers', models.IntegerField(null=True)),
                        ('updated_date', models.DateTimeField()),
                        ('year', models.IntegerField()),
                    ],
                    options={
                        'db_table': 'school',
                        'unique_together': {('organization_number', 'year')},
                    },
                ),
                migrations.CreateModel(
                    name='GroupCategory',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=255)),
                        ('canvas_id', models.IntegerField(db_index=True)),
                        ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_info.courseobservation')),
                    ],
                    options={
                        'db_table': 'group_category',
                    },
                ),
                migrations.CreateModel(
                    name='Group',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('canvas_id', models.IntegerField(db_index=True)),
                        ('name', models.CharField(max_length=255)),
                        ('description', models.CharField(blank=True, default=None, max_length=255, null=True)),
                        ('organization_number', models.CharField(db_index=True, max_length=9, null=True)),
                        ('created_at', models.DateTimeField()),
                        ('updated_date', models.DateTimeField(auto_now=True)),
                        ('members_count', models.IntegerField()),
                        ('aggregated', models.BooleanField(default=False)),
                        ('group_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_info.groupcategory')),
                    ],
                    options={
                        'db_table': 'group',
                    },
                ),
                migrations.CreateModel(
                    name='County',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('county_id', models.IntegerField()),
                        ('number_of_teachers', models.IntegerField()),
                        ('updated_date', models.DateTimeField()),
                        ('year', models.IntegerField()),
                    ],
                    options={
                        'db_table': 'county',
                        'unique_together': {('county_id', 'year')},
                    },
                ),
            ],
            database_operations=[],
        )
    ]
