# Generated by Django 3.2.13 on 2022-09-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment_activity', '0002_alter_enrollmentactivity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentactivity',
            name='course_name',
            field=models.CharField(help_text='Name of the course', max_length=255),
        ),
    ]
