# Generated by Django 3.2.13 on 2022-08-31 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment_activity', '0002_alter_enrollmentactivity_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='enrollmentactivity',
            table='enrollment_activity',
        ),
    ]
