# Generated by Django 3.2.13 on 2022-09-20 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment_activity', '0003_alter_enrollmentactivity_course_name'),
        ('enrollment_activity', '0003_alter_enrollmentactivity_table'),
    ]

    operations = [
    ]
