# Generated by Django 3.2.13 on 2022-09-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canvas_user_id', models.CharField(max_length=10)),
                ('group_id', models.CharField(max_length=10)),
                ('group_name', models.CharField(max_length=255)),
                ('group_description', models.CharField(max_length=255)),
            ],
        ),
    ]
