# Generated by Django 3.2.18 on 2024-02-14 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_users', '0002_auto_20220926_1323'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CanvasUser',
        ),
    ]
