# Generated by Django 4.2.10 on 2024-03-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRegistrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('group_id', models.IntegerField(blank=True, null=True)),
                ('group_name', models.CharField(blank=True, max_length=512, null=True)),
                ('date', models.DateField()),
                ('registrations', models.IntegerField()),
            ],
            options={
                'db_table': 'daily_registrations',
            },
        ),
    ]
