# Generated by Django 3.2.13 on 2022-06-22 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissionstatistics',
            name='canvas_id',
        ),
    ]
