# Generated by Django 3.2.13 on 2022-12-06 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_answerusergroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAnswerResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=1024)),
                ('group_name', models.CharField(blank=True, max_length=255, null=True)),
                ('group_id', models.CharField(blank=True, max_length=80, null=True)),
                ('question_statistics', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='open_responses', to='quizzes.questionstatistics')),
            ],
        ),
    ]
