# Generated by Django 3.2.13 on 2022-12-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_openanswerresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='openanswerresponse',
            name='submission_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
