# Generated by Django 3.2.13 on 2022-12-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_openanswerresponse_submission_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openanswerresponse',
            name='answer',
            field=models.CharField(max_length=5000),
        ),
    ]
