# Generated by Django 3.2.18 on 2024-02-14 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_alter_openanswerresponse_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerset',
            name='question_statistics',
        ),
        migrations.RemoveField(
            model_name='answerusergroup',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='openanswerresponse',
            name='question_statistics',
        ),
        migrations.RemoveField(
            model_name='questionstatistics',
            name='quiz_statistics',
        ),
        migrations.RemoveField(
            model_name='submissionstatistics',
            name='quiz_statistics',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='AnswerSet',
        ),
        migrations.DeleteModel(
            name='AnswerUserGroup',
        ),
        migrations.DeleteModel(
            name='OpenAnswerResponse',
        ),
        migrations.DeleteModel(
            name='QuestionStatistics',
        ),
        migrations.DeleteModel(
            name='QuizStatistics',
        ),
        migrations.DeleteModel(
            name='SubmissionStatistics',
        ),
    ]
