import os

from sqlalchemy.ext.declarative import declarative_base

ROOT_DIR = os.path.dirname(os.path.realpath(__file__)) + "/"

CA_FILE_NAME = os.getenv("CA_FILE_NAME")
CA_FILE_PATH = ROOT_DIR + f"../{CA_FILE_NAME}" if CA_FILE_NAME else None

CANVAS_DOMAIN = str(os.getenv("CANVAS_DOMAIN")).strip("'\"")
CANVAS_API_URL = f"https://{CANVAS_DOMAIN}/api/v1"
CANVAS_ACCESS_KEY = str(os.getenv("CANVAS_ACCESS_KEY")).strip("'\"")
CANVAS_ACCOUNT_ID = str(os.getenv("CANVAS_ACCOUNT_ID")).strip("'\"")

CANVAS_COUNTY_GROUP_CATEGORY_NAME = os.getenv("CANVAS_COUNTY_GROUP_CATEGORY_NAME")
CANVAS_COMMUNITY_GROUP_CATEGORY_NAME = os.getenv("CANVAS_COMMUNITY_GROUP_CATEGORY_NAME")
CANVAS_SCHOOL_GROUP_CATEGORY_NAME = os.getenv("CANVAS_SCHOOL_GROUP_CATEGORY_NAME")
CANVAS_SCHOOL_LEADER_COUNTY_GROUP_CATEGORY_NAME = os.getenv("CANVAS_SCHOOL_LEADER_COUNTY_GROUP_CATEGORY_NAME")
CANVAS_SCHOOL_LEADER_COMMUNITY_GROUP_CATEGORY_NAME = os.getenv("CANVAS_SCHOOL_LEADER_COMMUNITY_GROUP_CATEGORY_NAME")
CANVAS_PRINCIPAL_ROLE_TYPE = os.getenv("CANVAS_PRINCIPAL_ROLE_TYPE")
CANVAS_STUDENT_ROLE_TYPE = os.getenv("CANVAS_STUDENT_ROLE_TYPE")

DB_HOST = os.getenv("DB_HOST")
DB_PORT = os.getenv("DB_PORT")
DB_DATABASE = os.getenv("DB_DATABASE")
DB_USERNAME = os.getenv("DB_USERNAME")
DB_PASSWORD = os.getenv("DB_PASSWORD")
MYSQL_ROOT_PASSWORD = os.getenv("MYSQL_ROOT_PASSWORD")

# NB! Hour and mintue of the day are in UTC
DATABASE_REFRESH_HOUR = str(os.getenv("DATABASE_REFRESH_HOUR")).zfill(2) if os.getenv("DATABASE_REFRESH_HOUR") else "03"
DATABASE_REFRESH_MINUTE = str(os.getenv("DATABASE_REFRESH_MINUTE")).zfill(2) if os.getenv(
    "DATABASE_REFRESH_MINUTE") else "00"

MYSQL_VARCHAR_DEFAULT_LENGTH = 255
MYSQL_CASCADE = "CASCADE"
Base = declarative_base()
STRFTIME_FORMAT = "%Y-%m-%d %H:%M:%S"
