FROM nginx:1.19.0
RUN apt update && apt install inetutils-ping dnsutils net-tools vim procps -y
COPY default.conf /etc/nginx/conf.d/default.conf
COPY nginx-selfsigned.crt /etc/ssl/certs/nginx-selfsigned.crt
COPY nginx-selfsigned.key /etc/ssl/private/nginx-selfsigned.key
#ARG NGINX_SERVER_NAME
ARG STATISTICS_API_PORT
ARG STATISTICS_API_HOST
#RUN sed -i "s/NGINX_SERVER_NAME/${NGINX_SERVER_NAME}/g" /etc/nginx/conf.d/default.conf
RUN sed -i "s/STATISTICS_API_PORT/${STATISTICS_API_PORT}/g" /etc/nginx/conf.d/default.conf
RUN sed -i "s/STATISTICS_API_HOST/${STATISTICS_API_HOST}/g" /etc/nginx/conf.d/default.conf
