# Generated by Django 3.2.13 on 2022-06-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('canvas_userid', models.CharField(max_length=10)),
                ('asset_code', models.CharField(max_length=255)),
                ('context_id', models.IntegerField()),
                ('context_type', models.CharField(max_length=255)),
                ('visited_at', models.DateTimeField()),
                ('visited_url', models.URLField()),
                ('interaction_seconds', models.IntegerField()),
                ('asset_icon', models.CharField(max_length=255)),
                ('asset_readable_category', models.CharField(max_length=255)),
                ('asset_name', models.CharField(max_length=255)),
                ('context_name', models.CharField(max_length=255)),
            ],
        ),
    ]
