# Generated by Django 3.2.13 on 2022-09-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_alter_history_interaction_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='asset_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='asset_icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='asset_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='asset_readable_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='context_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='context_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='visited_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
