# Generated by Django 3.2.13 on 2022-09-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_auto_20220901_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='context_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
