# Generated by Django 3.2.18 on 2024-02-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_alter_history_context_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='visited_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
