# Generated by Django 3.2.18 on 2024-02-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_alter_history_visited_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='asset_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
