# Generated by Django 3.2.13 on 2022-11-01 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canvas_id', models.CharField(max_length=80)),
                ('course_id', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=512)),
                ('published', models.BooleanField()),
                ('position', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ModuleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canvas_id', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=512)),
                ('position', models.IntegerField()),
                ('url', models.URLField(max_length=255)),
                ('type', models.CharField(max_length=80)),
                ('published', models.BooleanField(blank=True, null=True)),
                ('completion_type', models.CharField(max_length=255)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_items', to='canvas_modules.module')),
            ],
        ),
        migrations.CreateModel(
            name='FinnishMarkCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=80)),
                ('group_name', models.CharField(max_length=512)),
                ('count', models.IntegerField(default=0)),
                ('module_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fm_counts', to='canvas_modules.moduleitem')),
            ],
        ),
        migrations.CreateModel(
            name='FinnishedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=80, null=True)),
                ('completed', models.BooleanField()),
                ('module_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fm_students', to='canvas_modules.moduleitem')),
            ],
        ),
    ]
