# Generated by Django 3.2.13 on 2022-11-01 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finnishedstudent',
            name='module_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='canvas_modules.moduleitem'),
        ),
        migrations.AlterField(
            model_name='finnishmarkcount',
            name='module_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_groups', to='canvas_modules.moduleitem'),
        ),
    ]
