name: Periodic API health check

# This workflow is triggered on pushes to the repository.
on:
  schedule:
    # Runs at 0 minutes over the 4th hour on each day. Cron syntax
    - cron:  '*/5 * * * *'
  push:

jobs:
  health-test:
    env:
      API_BASE_URL: https://statistics-api-staging.azurewebsites.net
      COURSE_ID: 360
      MUNICIPALITY_ID: "0301"
      DATA_MAX_AGE: 7200

      # This job runs on Linux
    runs-on: ubuntu-latest

    steps:
      # GitHub repository checkout
      - name: GitHub repository checkout
        uses: actions/checkout@v1


      - name: Check if data from API is less than 7200 seconds old
        run: |
          chmod 700 $GITHUB_WORKSPACE/.github/health_test_src/do_health_test.py
          $GITHUB_WORKSPACE/.github/health_test_src/do_health_test.py