name: API health check

# This workflow is triggered on pushes to the repository.
on:
  schedule:
    # Runs at 0 minutes over the 4th hour on each day. Cron syntax
    - cron:  '*/5 * * * *'
  push:

jobs:
  health-test:
    if: github.ref=='refs/heads/staging'

    env:
      API_BASE_URL: https://statistics-api-staging.azurewebsites.net
      COURSE_ID: 360
      MUNICIPALITY_ID: 0301

      # This job runs on Linux
    runs-on: ubuntu-latest

    steps:
      - name: Check if data from API is less than 7200 seconds old
        run: |
          curl -s "${API_BASE_URL}/api/statistics/primary_schools/municipality/${MUNICIPALITY_ID}/course/${COURSE_ID}" | \
          python3 -c "import sys; import json; from datetime import datetime; date_str = json.loads(sys.stdin.read())['Result'][0]['date']; date_obj = datetime.fromisoformat(date_str[:-1]); time_diff = datetime.now() - date_obj; assert time_diff.total_seconds() < 7200"