name: Tests

# Controls when the action will run. Triggers the workflow on manual trigger or push
on:
  workflow_dispatch:
  push:

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    env:
      DB_HOST: 127.0.0.1
      DB_DATABASE: canvas-api
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_PORT: 3306
      KPAS_DOMAIN: kpas-lti-staging-kpas.azurewebsites.net
      DJANGO_SECRET_KEY: not_secret_key

    steps:
        # GitHub repository checkout
      - name: GitHub repository checkout
        uses: actions/checkout@v1

      - name: Install python depedencies
        run: |
          sudo apt-get install python3-setuptools
          python3 -m pip install -r requirements.txt

      - name: Start MySQL service
        run: sudo systemctl start mysql.service

      - name: Import test data to MySQL
        run: mysql -uroot -proot < $GITHUB_WORKSPACE/statistics_api/tests/data/canvas_api_test_data.sql

      - name: Run Django unit tests
        run: |
          PYTHONPATH="${GITHUB_WORKSPACE}" python3 manage.py test --keepdb

          